### ISSUE TITLE
deletes all files in output folder if paths are not prefixed with '/'

### ISSUE THREAD

**Issue by alvint** [agarzola/gulp-deleted#1]
All other plugins work properly without the leading slash and some require no leading slash. The current operation is very dangerous; if the leading slash is missing the plugin deletes all files in the output folder matching the second parameter.

**Comment by alvint** [comment]
Actually, now it doesn't seem to be working at all. Perhaps I'm not calling it correctly? I'm calling it this way:

``` js
function buildHtml() {
  return gulp.src(config.src.html)
  .pipe(plugins.deleted('/app', 'app/**/*.html'))
  .pipe(plugins.changed('app'))
    .pipe(plugins.if(config.mode === 'production', plugins.minifyHtml()))
    .pipe(gulp.dest('app'))
}
```

**Comment by oliverfoster** [comment]
Thanks for your comments alvint. I hadn't realised anyone else was interested in this plugin. It was more for personal use and experimentation.

We can change that however.

I'm away from home until the 5th of January. I can help you then / make amends if that works? Otherwise you're more than welcome to fork the code, it isn't very long and I don't mind accepting pull requests either, I can do that on my phone. 

This code will be under an MIT license if I get a chance to set it up properly. 
- Ollie.

**Comment by oliverfoster** [comment]
On further inspection it looks as though I wrote it for absolute path names.  So to use the folder 'app' from the current path you'd need to:

```
var path = require('path');
var destinationFolder = path.join(process.cwd(), "app");
```

And for source you'd need:

```
var sourceFolder = path.join(process.cwd(), "app/**/*.html");
```

To go into:

```
deleted(destinationFolder, [ sourceFolder ]) 

```

As a side note:

I'd suggest having a closer at file paths: 
"/app" would always be from the root folder of the operating system. 
"app" would always be relative to the context decided by the program or the program's current working directory
"../app" is back one, etc. 

I hope that helps for the moment.

**Comment by oliverfoster** [comment]
It occurs to me that I probably need to ask you for a discription of what you expect this code to do. I'm not sure my description of what it does is very clear so there is a chance that it's intended purpose is not your requirement. 

Let me know what you wanted it for.

It should delete everything in the destination folder which does not exist in the source stream. It does this by comparing the filenames only. So if destination X contains file 'app/tests.html' and source Y doesn't contain 'app/tests.html' the code will delete the file from X.

**Comment by ghost** [comment]
@oliverfoster 
great idea, really useful in conjunction with gulp-change and gulp-imagemin. Unfortunately it is not working with relative paths as standard node packages do. I'll look into the code as soon as I have time in the following weeks and request a pull.
Thank you for your effort.

**Comment by oliverfoster** [comment]
cool, thanks alen, did you want to take it? i'm not using it anymore

i can transfer it to you if ya like

**Comment by agarzola** [comment]
Closing this as stale. @alvint: please feel free to chime in here if this is still an issue for you.
