### ISSUE TITLE
File Aliases

### ISSUE THREAD

**Issue by tednoelker** [agarzola/gulp-deleted#17]
Stubbled across your package on NPM and so far it's providing useful for keeping my dist and src directories in sync. One limitation that I've noticed is for files that are renamed (e.g. `.scss` files that are renamed to `.css` in the dist directory).

Would you accept a PR to add support for aliasing in the diff comparison?

**Comment by bvansteelandt** [comment]
Coincidentally, this is the same issue that I'm running into right now. +1 for the PR

**Comment by agarzola** [comment]
Hello, @tednoelker & @bvansteelandt! 👋 

Apologies for my radio silence! I had not received notifications about this issue.

By all means, contributions are quite welcome! @tednoelker if you’re still game to submit a PR, please don’t hesitate to do so. I promise to review it in a timely fashion. 😄

**Comment by agarzola** [comment]
I find myself in need of this functionality, so I’m working on it today.

**Comment by agarzola** [comment]
This functionality is now supported in v2.1.0. The README includes instructions on how to opt into this functionality.
