### ISSUE TITLE
Are you accepting PR?

### ISSUE THREAD

**Issue by HannanAkbar** [agarzola/gulp-deleted#4]
Is this plugin deprecated?
I saw a fork `gulp-deleted2` on NPM. Why there are two versions?
https://github.com/joachimprinzbach/gulp-deleted

**Comment by oliverfoster** [comment]
He forked. I offered to give him the repo as I don't use it. Conversation died.
If you want it it's yours, I've no need for it now.

**Comment by HannanAkbar** [comment]
After testing almost all gulp clean/delete plugins I'm settled with this and using it along with some other packages to clean builds.

I would love to take it further. 👍 
Should I just fork it? What about the NPM package?

**Comment by oliverfoster** [comment]
I'll transfer it. You should have access to the npm package once you're owner. 👍

**Comment by agarzola** [comment]
@oliverfoster I’m interested in this package and would like to see it maintained. If this conversation has also died, I would not mind taking it over for maintenance.

**Comment by oliverfoster** [comment]
I can transfer if you're willing to accept?

**Comment by agarzola** [comment]
@oliverfoster Very much so! I’m `agarzola` both here and on npmjs.org.

**Comment by agarzola** [comment]
@oliverfoster Hi! Apologies, I missed the repo transfer email yesterday morning. I ran across it this morning, but the transfer had already expired. Care to resend?

**Comment by oliverfoster** [comment]
done

**Comment by oliverfoster** [comment]
you should get control over the npm once you're owner i hope?

**Comment by agarzola** [comment]
Thanks, @oliverfoster! I accepted the GitHub transfer request. However, I don’t think npm package ownership is in any way tied to Git repo ownership. Here are the instructions on npmjs.org’s website: https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

**Comment by oliverfoster** [comment]
:+1:

**Comment by oliverfoster** [comment]
remove me once you're happy :)

**Comment by agarzola** [comment]
@oliverfoster The package appears under my packages, but I don’t seem to have admin privileges. Could you check to make sure?

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/61460691-29d41000-a967-11e9-858e-a30e9f075271.png)

There isn't any other UI for access control, other than the remove button.

**Comment by oliverfoster** [comment]
you may have to republish

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/61460781-5e47cc00-a967-11e9-9bc4-48df889ba257.png)
i'm down as the only collaborator.

**Comment by agarzola** [comment]
That makes sense. I’ll update `package.json` to point to the new GitHub URL and publish that. I’ll report back here.

**Comment by agarzola** [comment]
You were absolutely right. I published a new patch version pointing at the new repo URL and updating the maintainers array, and now it shows me the _Admin_ tab. I removed you as a maintainer, so we’re good to go.

Thanks again, @oliverfoster! I look forward to carrying the torch from now on. :)

**Comment by oliverfoster** [comment]
Good luck ;)
